GET http://localhost:3000/private

###

POST http://localhost:3000/auth/login HTTP/1.1
content-type: application/json

{
    "email": "admin",
    "password": "admin"
}

###

POST http://localhost:3000/auth/logout

###

post http://localhost:3000/auth/register
content-type: application/json

{
    "email": "admin2",
    "password": "admin"
}

### Create confernce

post http://localhost:3000/conference/create
content-type: application/json

{
    "name": "why making softwere is hard"
}

### Update confernce

post http://localhost:3000/conference/update
content-type: application/json

{
    "name": "Updated name of project",
    "conferenceID": "ca0d7c22-768b-49db-8250-321e12e1754d"
}

### Get conference data

post http://localhost:3000/conference/data
content-type: application/json

{
    "conferenceID": "ca0d7c22-768b-49db-8250-321e12e1754d"
}

### remove data
post http://localhost:3000/conference/remove
content-type: application/json

{
    "conferenceID": "a4eb123d-1c44-454a-a287-f4a3c689740"
}

### add attendess
post http://localhost:3000/conference/attendees/add
content-type: application/json

{
    "users": [27,29,30],
    "conferenceID": "ca0d7c22-768b-49db-8250-321e12e1754d"
}

### remove attendess
post http://localhost:3000/conference/attendees/remove
content-type: application/json

{
    "users": [27,29,30],
    "conferenceID": "ca0d7c22-768b-49db-8250-321e12e1754d"
}

### get conferncess for user
post http://localhost:3000/user/conferences

### get attendees
post http://localhost:3000/conference/attendees
content-type: application/json

{
    "conferenceID": "ca0d7c22-768b-49db-8250-321e12e1754d"
}