GET http://localhost:3000/private

###

POST http://localhost:3000/auth/login HTTP/1.1
content-type: application/json

{
    "email": "admin",
    "password": "admin"
}

###

POST http://localhost:3000/auth/logout

###

post http://localhost:3000/auth/register
content-type: application/json

{
    "email": "admin2",
    "password": "admin"
}

### Create confernce

post http://localhost:3000/conference/create
content-type: application/json

{
    "name": "why making softwere is hard"
}

### Update confernce

post http://localhost:3000/conference/update

{
    "name": "Updated name of project",
    "conferenceID": "457277d0-cb1e-463f-b03d-25017a33e554"
}